#!/usr/bin/env python
Import([
  "env",
  "ld_flags",
  "cpp_flags",
  "compiler",
  "defines",
])
build_dir = "../../build/"
prog_name = "image strip"
src_dir = "."
thirdparty_dir = "../../thirdparty/"
inc_path = [
  "../../src",
  src_dir,
  thirdparty_dir + "include",
]
lib_path = []
used_libs = []
sources = [
  Glob("*.cpp"),
]

env.Append(CPPDEFINES = defines)
env.Append(CXXFLAGS = cpp_flags)
env.Program(
  target = build_dir + prog_name,
  source = sources,
  CXX = compiler,
  CXXFLAGS = cpp_flags,
  LIBPATH = lib_path,
  CPPPATH = inc_path,
  LINKFLAGS = ld_flags,
  LIBS = used_libs
) # env.Program
