#!/usr/bin/env python

Import([
  "env",
  "ld_flags",
  "cpp_flags",
  "compiler",
  "defines",
])

build_dir = "../../build/"
prog_name = "code-to-image"
src_dir = "../../src/"
thirdparty_dir = "../../thirdparty/"
inc_path = [
  ".",
  src_dir,
  thirdparty_dir + "include",
]
lib_path = []
used_libs = []
sources = [
  Glob("*.cpp"),
  src_dir + "util/error.cpp",
  src_dir + "util/str-util.cpp",
  src_dir + "util/path.cpp",
  src_dir + "util/file/file.cpp",
  src_dir + "util/math/vec-util.cpp",
  src_dir + "util/math/random.cpp",
  src_dir + "util/math/mat.cpp",
  src_dir + "util/math/rect.cpp",
  src_dir + "graphic/image/image-io.cpp",
  src_dir + "graphic/image/image.cpp",
  src_dir + "graphic/sprite/sprite.cpp",
  src_dir + "graphic/image/palette.cpp",
  src_dir + "graphic/image/color.cpp",
  src_dir + "graphic/image/color-blend.cpp",
  src_dir + "graphic/util/graphic-util.cpp",
  src_dir + "graphic/util/convert.cpp",
]

env.Program(
  target = build_dir + prog_name,
  source = sources,
  LIBPATH = lib_path,
  LIBS = used_libs,
  CXX = compiler,
  CPPDEFINES = defines,
  CXXFLAGS = cpp_flags,
  LINKFLAGS = ld_flags,
  CPPPATH = inc_path,
)
