#!/usr/bin/env python
Import([
  "env",
  "ld_flags",
  "cpp_flags",
  "compiler",
  "defines",
])
build_dir = "../../build/"
prog_name = "tilemap-gen"
src_dir = "../../src/"
thirdparty_dir = "../../thirdparty/"
inc_path = [
  "../../src",
  src_dir,
  thirdparty_dir + "include",
]
lib_path = [thirdparty_dir + "lib/yaml-cpp"]
used_libs = ["yaml-cpp"]
sources = [
  src_dir + "graphic/util/graphic-util.cpp",
  src_dir + "graphic/util/convert.cpp",
  src_dir + "graphic/image/image.cpp",
  src_dir + "graphic/image/image-io.cpp",
  src_dir + "graphic/image/color-blend.cpp",
  src_dir + "graphic/image/color.cpp",
  src_dir + "graphic/image/table.cpp",
  src_dir + "graphic/sprite/sprite.cpp",
  src_dir + "util/file/file.cpp",
  src_dir + "util/file/yaml.cpp",
  src_dir + "util/math/vec-util.cpp",
  src_dir + "util/math/mat.cpp",
  src_dir + "util/math/random.cpp",
  src_dir + "util/error.cpp",
  src_dir + "util/path.cpp",
  src_dir + "util/str-util.cpp",
  Glob("*.cpp"),
]

env.Append(CPPDEFINES = defines)
env.Append(CXXFLAGS = cpp_flags)
env.Program(
  target = build_dir + prog_name,
  source = sources,
  CXX = compiler,
  CXXFLAGS = cpp_flags,
  LIBPATH = lib_path,
  CPPPATH = inc_path,
  LINKFLAGS = ld_flags,
  LIBS = used_libs
) # env.Program
