#!/usr/bin/env python
Import([
  "env",
  "is_linux",
  "is_debug",
  "ld_flags",
  "cpp_flags",
  "defines",
  "is_64bit",
  "compiler",
])

prog_name = "empty-test"
build_dir = "../../build/"
src_dir = "../../src/"
thirdparty_dir = "../../thirdparty/"
inc_path = [
  ".",
  src_dir,
  thirdparty_dir + "include",
]
lib_path = []
used_libs = []
sources = [
  #Glob(src_dir + "util/math/*.cpp"),
  #Glob(src_dir + "hpw/*.cpp"),
  Glob("*.cpp"),
]
#inc_path.extend([thirdparty_dir + "include/_windows_only"])

env.Program(
  target = build_dir + prog_name,
  source = sources,
  CXXFLAGS = cpp_flags,
  CPPDEFINES = defines,
  LIBPATH = lib_path,
  CPPPATH = inc_path,
  LINKFLAGS = ld_flags,
  LIBS = used_libs,
  CXX = compiler
)
