#!/usr/bin/env python
''' :file: скрипт удаляющий файлы билда '''

if __name__ != "__main__":
  print("is not a python module")

import helper

helper.rem_all('**/delme.html')
helper.rem_all('**/*.exe')
helper.rem_all('**/*.elf')
helper.rem_all('**/*.elf32')
helper.rem_all('**/*.elf64')
helper.rem_all('**/vgcore.*')
helper.rem_all('**/cpplint.txt')
helper.rem_all('**/gmon.svg')
helper.rem_all('**/*.obj')
helper.rem_all('**/*.o')
helper.rem_all('**/*.os')
helper.rem_all('**/*.out')
helper.rem_all('**/*.gch')
helper.rem_all('**/log.txt')
helper.rem_all('**/*.gcda')
helper.rem_all('**/*.gcno')
helper.rem_all('**/*.hpw_replay')
helper.rem_all('**/imgui.ini')
helper.rem_all('**/cpplint.txt')
helper.rem_all('**/perf.data.old')
helper.rem_all('**/perf.data')
helper.rem_dir('__pycache__')
helper.rem_dir('script/__pycache__')
helper.rem_dir('pgo', True)
helper.rem_if_exist('build/bin/HPW.exe')
helper.rem_if_exist('build/bin/HPW')
helper.rem_if_exist('build/test.yml')
helper.rem_if_exist('.sconsign.dblite')
helper.rem_all('.tmp/*.txt')
helper.rem_all('.tmp/*.pickle')
helper.rem_dir('build/screenshots/', True)
helper.rem_all('build/replays/*')
helper.rem_dir('build/replays/', True)
helper.rem_dir('build/plugin/', True)
helper.rem_all('build/debug.txt')
helper.rem_all('build/data.zip')
helper.rem_dir('build/config/', True)
helper.rem_dir('build/info/', True)
