#!/bin/sh
mv .tmp/new_data_zip_file.txt .tmp/old_data_zip_file.txt
7z l build/data.zip > .tmp/new_data_zip_file.txt
git diff --no-index new_data_zip_file.txt old_data_zip_file.txt > diff_data_zip_file.txt
printf "\n" >> $1 # не трогать сообщение, отступить
cat diff_data_zip_file.txt >> $1
cat diff_data_zip_file.txt
rm diff_data_zip_file.txt
exit 0
