#include <omp.h>

#include <source_location>
#include <unordered_map>
#include <string_view>
#include <functional>
#include <filesystem>
#include <algorithm>
#include <algorithm>
#include <stdexcept>
#include <stdexcept>
#include <iostream>
#include <stdfloat>
#include <cstdint>
#include <cstring>
#include <codecvt>
#include <cassert>
#include <cstdlib>
#include <sstream>
#include <fstream>
#include <utility>
#include <iomanip>
#include <numeric>
#include <ranges>
#include <random>
#include <atomic>
#include <chrono>
#include <string>
#include <thread>
#include <format>
#include <deque>
#include <mutex>
#include <cmath>
#include <ctime>
#include <array>
#include <list>
#include <map>

#include "util/math/num-types.hpp"
#include "util/math/vec-util.hpp"
#include "util/math/xorshift.hpp"
#include "util/math/polygon.hpp"
#include "util/math/average.hpp"
#include "util/math/circle.hpp"
#include "util/math/random.hpp"
#include "util/math/timer.hpp"
#include "util/math/rect.hpp"
#include "util/math/mat.hpp"
#include "util/math/vec.hpp"

#include "util/vector-types.hpp"
#include "util/mem-types.hpp"
#include "util/hpw-util.hpp"
#include "util/platform.hpp"
#include "util/str-util.hpp"
#include "util/safecall.hpp"
#include "util/mempool.hpp"
#include "util/pparser.hpp"
#include "util/unicode.hpp"
#include "util/macro.hpp"
#include "util/error.hpp"
#include "util/path.hpp"
#include "util/str.hpp"
#include "util/log.hpp"
