#!/usr/bin/env python
Import([
  "env",
  "is_linux",
  "is_debug",
  "ld_flags",
  "cpp_flags",
  "compiler",
  "defines",
  "is_64bit",
])
build_dir = "../../build/"
prog_name = "table gen"
src_dir = "../../src/"
thirdparty_dir = "../../thirdparty/"
inc_path = [
  "../../src",
  src_dir,
  thirdparty_dir + "include",
]
lib_path = []
used_libs = []
sources = [
  Glob("*.cpp"),
  src_dir + "graphic/image/color.cpp",
  src_dir + "graphic/util/convert.cpp",
  src_dir + "util/file/file.cpp",
  src_dir + "util/str-util.cpp",
  src_dir + "util/error.cpp",
]
defines.append(["-DNOUSE_TABLE"])

env.Program(
  target = build_dir + prog_name,
  source = sources,
  CXX = compiler,
  CXXFLAGS = cpp_flags,
  LIBPATH = lib_path,
  CPPPATH = inc_path,
  LINKFLAGS = ld_flags,
  LIBS = used_libs,
  CPPDEFINES = defines,
) # env.Program
