#!/usr/bin/env python
from script.helper import *
Import(['env'])

hpw_config = env['hpw_config']
assert hpw_config

build_dir = "../../build/bin/"
prog_name = "table gen"
src_dir = "../../src/"
thirdparty_dir = "../../thirdparty/"
inc_path = [
  "../../src",
  src_dir,
  thirdparty_dir + "include",
]
lib_path = []
used_libs = []
sources = [
  Glob("*.cpp"),
  src_dir + "graphic/image/color.cpp",
  src_dir + "graphic/util/convert.cpp",
  src_dir + "util/file/file.cpp",
  src_dir + "util/file/file-io.cpp",
  src_dir + "util/str-util.cpp",
  src_dir + "util/error.cpp",
]
hpw_config.cxx_defines.append(["-DNOUSE_TABLE"])

env.Program(
  target = build_dir + prog_name,
  source = sources,
  LIBPATH = lib_path,
  LIBS = used_libs,
  CPPDEFINES = hpw_config.cxx_defines,
  CXXFLAGS = hpw_config.cxx_flags,
  LINKFLAGS = hpw_config.cxx_ldflags,
  CPPPATH = inc_path,
) # env.Program
